# -*- coding: utf-8 -*-
"""SIMRITHPYTHONLONDONSPORTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2CwOWwMefAefFpy16ZfTMTBsHCIexI4
"""

import requests
import pandas as pd
#so i went to open active catalog where every organisation posts the data publicly and then i used python to access it and found 4 catalogs
# this gets the master list of all UK feeds
catalog_url = "https://openactive.io/data-catalogs/data-catalog-collection.jsonld"
response = requests.get(catalog_url)
data = response.json()

print(data)

# see all the catalog links inside it
for item in data["hasPart"]:
    print(item)

# let's first see what's actually inside the catalog
print(type(catalog))
print(catalog.keys())
print(catalog)

# print all the provider URLs
for url in catalog["dataset"]:
    print(url)

import time
havering,enfield,barking

london_providers = [
    "https://southwarkcouncil-oa.leisurecloud.net/OpenActive/",
    "https://towerhamletscouncil.gs-signature.cloud/OpenActive/",
    "https://visionredbridge.gs-signature.cloud/OpenActive/",
    "https://data.everyoneactive.com/OpenActive/",
    "https://inside.ledleisure.co.uk/OpenActive/",
]

all_records = []

for provider_url in london_providers:
    try:
        r = requests.get(provider_url, timeout=10).json()
        print(provider_url)
        print(r.keys())
        print("---")
    except Exception as e:
        print(f"failed: {provider_url} - {e}")
    time.sleep(1)

# lets look inside one provider page to find the actual feed URL
r = requests.get("https://data.everyoneactive.com/OpenActive/")
print(r.text[:2000])

from bs4 import BeautifulSoup
import json

r = requests.get("https://data.everyoneactive.com/OpenActive/")
soup = BeautifulSoup(r.text, "html.parser")

# find the JSON-LD script tag which contains the feed URLs
script = soup.find("script", {"type": "application/ld+json"})
if script:
    data_json = json.loads(script.string)
    print(json.dumps(data_json, indent=2))

# this is the actual data feed URL we just found
feed_url = "https://opendata.leisurecloud.live/api/feeds/EveryoneActive-live-session-series"

r = requests.get(feed_url).json()
print("Number of items:", len(r["items"]))
print("First item:", r["items"][0])

# convert to a clean dataframe and save as CSV
records = []

for item in r["items"]:
    if item["state"] == "deleted":
        continue
    data = item.get("data", {})
    location = data.get("location", {}) or {}
    address = location.get("address", {}) or {}
    geo = location.get("geo", {}) or {}
    activities = data.get("activity", []) or []
    activity_names = [a.get("prefLabel", "") for a in activities]

    records.append({
        "name": data.get("name", ""),
        "activity_type": ", ".join(activity_names),
        "venue": location.get("name", ""),
        "address": address.get("streetAddress", ""),
        "town": address.get("addressLocality", ""),
        "postcode": address.get("postalCode", ""),
        "latitude": geo.get("latitude", None),
        "longitude": geo.get("longitude", None),
        "provider": "Everyone Active",
    })

df = pd.DataFrame(records)
print(df.shape)
print(df.head())
df.to_csv("openactive_london.csv", index=False)
print("saved!")

# filter to London only using postcode
# London postcodes start with E, N, W, SE, SW, EC, WC, NW, BR, CR, DA, EN, HA, IG, KT, RM, SM, TW, UB, WD

london_postcode_prefixes = (
    'E', 'N', 'W', 'SE', 'SW', 'EC', 'WC', 'NW',
    'BR', 'CR', 'DA', 'EN', 'HA', 'IG', 'KT', 'RM', 'SM', 'TW', 'UB', 'WD'
)

df_london = df[df['postcode'].str.startswith(london_postcode_prefixes, na=False)]

print("Total records:", len(df))
print("London records:", len(df_london))
print(df_london.head())

from google.colab import files
files.download("openactive_london.csv")